### ISSUE TITLE
Praktikumsangebote überarbeiten

### ISSUE THREAD

**Issue by bkleinen** [imimap/imimap#230]
- Ort wäre gut in der Übersicht
- Funktioniert der PDF upload? brauchen wir den? rausnehmen? restaurieren?

**Comment by JuliaZamaitat** [comment]
Ort funktioniert jetzt!

**Comment by JuliaZamaitat** [comment]
PDF Upload funktioniert, kann ganz sinnvoll sein, würde ich so lassen.
