### ISSUE TITLE
Praktikaeinträge ohne gültigen Zeitraum ablehnen 

### ISSUE THREAD

**Issue by JuliaZamaitat** [imimap/imimap#246]
Es ist bisher möglich, dass das Enddatum des Praktikums vor dem Startdatum liegt und dann Minusstunden angezeigt werden auf dem neuen Server. Muss behoben werden.

**Comment by bkleinen** [comment]
Bitte aufnehmen in https://github.com/imimap/imimap/blob/master/app/models/internship_duration.rb

- speichern dennoch zulassen.
