### ISSUE TITLE
Runden der Wochen bei Dauer des Praktikums

### ISSUE THREAD

**Issue by JuliaZamaitat** [imimap/imimap#247]
Bisher erscheinen zig Nachkommastellen bei der Dauer der Praktika.

**Comment by bkleinen** [comment]
Mo-Fr bei exakt 19 Wochen ergibt 18,57 - dies muss man also entweder weiter sehen oder es wird durch das adjust day in internship duration ohnehin abgefangen. Ist noch abzuwägen, adjust day ist vermutlich genauer weil es den tatsächlichen Wochentag mit einbezieht.

**Comment by JuliaZamaitat** [comment]
@weeks = (@days.to_f / 7).round 

Das wäre unser Vorschlag, dann ist es aber nicht genau auf den Tag. Sollen wir diese mit einbeziehen?
