### ISSUE TITLE
Mehrfachauswahl bei Programmiersprachen bei neuen Internships funktioniert nicht

### ISSUE THREAD

**Issue by JuliaZamaitat** [imimap/imimap#294]
trotz des Codes hier im in views/internships/new.html.erb: 
  
<%= f.select :programming_language_ids, @programming_languages, {}, { **:multiple => true**, class: 'chzn-select', hide_label: true} %>

We don't know why :)

**Comment by JuliaZamaitat** [comment]
Wahrscheinlich weil sich ActiveAdmin den View woanders her holt...

**Comment by bkleinen** [comment]
welcher branch? (bitte auch wenn kaputt pushen, dann kann ich direkt reingucken)

**Comment by JuliaZamaitat** [comment]
Im Master!

**Comment by bkleinen** [comment]
es hatte tatsächlich mit den permitted params in active record zu tun, speziell damit, den hash den es laut Dokumentation braucht korrekt an die Methode zu übergeben. siehe
# https://coderwall.com/p/g4al5g/strong-parameters-with-has_and_belongs_to_many
# and especially
# https://github.com/activeadmin/activeadmin/blob/master/docs/
# 2-resource-customization.md#setting-up-strong-parameters

sowie dem ausprobieren zur parameterübergabe in spec-api/method_call_*

den key richtig zu benennen hat aber auch geholfen :)
