### ISSUE TITLE
Story: Praktikumsantrag als PDF 5 SP

### ISSUE THREAD

**Issue by bkleinen** [imimap/imimap#314]
Prawn scheint immernoch state of the art zu sein: 
https://pspdfkit.com/blog/2018/generating-pdfs-with-ruby/

**Comment by lotteunckell** [comment]
ToDo: Statt der Ausfüllhinweise als Anhang zum generiwerten PDF eine Liste aus der IMImap ausdrucken lassen, was nach der Anmeldung zum Praktikum weiter zu tun ist.

**Comment by bkleinen** [comment]
- [ ] bitte noch Tests für weiteren Inhalt ergänzen
- [ ] offene Module kann & muss raus (StuPo Änderung)
- [ ] Einverständnis zur Datenspeicherung IMI-Map mit rein
