### ISSUE TITLE
Rausfinden, wo in Rails der richtige Platz für scoped Calls ist

### ISSUE THREAD

**Issue by lotteunckell** [imimap/imimap#363]
Helpermethoden find_internship_with_company_address, find_internship z.B. lieber ins Model auslagern?

**Comment by bkleinen** [comment]
Überlegungen: 
MVC: current_user gehört in den Controller, das Modell sollte sich nicht mit Zugriffsrechten beschäftigen oder mindestens nicht den current_user kennen - evtl. wie bei der Antwort hier:
https://stackoverflow.com/questions/8186048/rails-scope-find-with-current-user
- natürlich wie immer nicht die als "richtig" bewertete Antwort, sondern die darunter von nathanvda:



I like to do this as follows:

class Product

  scope :by_user, lambda { |user|
    where(:owner_id => user.id) unless user.admin?
  }

end

this allows you to write the following in your controller:

Product.by_user(current_user).find(params[:id])

**Comment by bkleinen** [comment]
Dokumentation Scopes: https://guides.rubyonrails.org/active_record_querying.html#scopes
- und hier der Grund: https://brakemanscanner.org/docs/warning_types/unscoped_find/
