### ISSUE TITLE
Vorschläge für Companies fertigstellen

### ISSUE THREAD

**Issue by lotteunckell** [imimap/imimap#371]
- [x] Fall 1: Der eingegebene Firmenname und der ein ergebnis stimmen exakt überein
   - Wir lassen die Option, eine neue Company zu erstellen im Frontend da
   - Im Backend werden diese Companies aber zusammengeführt
- [x] Fall 2: Der Name kommt in den gefundenen Companies vor, allerdings nicht exakt
   - Q: Wie viele Ergebnisse wollen wir dann anzeigen lassen?
   - A: Alle gefundenen anzeigen lassen!
- [x] Fall 3: Es gibt kein Match
   - Dann den Auswahlview einfach überspringen
- [x] Abfangen was passiert, wenn der Name blank ist
<br>

- [ ] Evtl. auch ähnliche Companies finden lassen (Levenshtein distance)

**Comment by bkleinen** [comment]
Bitte updaten - kann der zugunsten der neuen Stories geschlossen werden?
