### ISSUE TITLE
Story: Als Firma / Company möchte ich nicht frei in der Suche angezeigt werden

### ISSUE THREAD

**Issue by bkleinen** [imimap/imimap#387]
als Methode im Model; 
max n (= 7?) anzeigen - testen auf realen Daten was Sinn macht, 
evtl über Konfiguration bei Firmen wie Google/Fraunhofer ausnahmen falls es die häufiger gibt
ggfs. bei kurzen Namen zb. LG nur die kürzesten x (x=3?) angeben

**Comment by lotteunckell** [comment]
Nachdem wir auf die realen Daten geschaut haben:
- Es gibt ein unteres Limit, um eine Suche überhaupt zuzulassen als Länge des kürzesten Firmennamens mit `Company.pluck('length(name)').sort.first`. 
   - Wenn die Länge einer Suchanfrage darunter liegt muss entweder erneut genauer gesucht werden, oder es kann eine Firma mit diesem Namen angelegt werden.
- Es werden bis zu einem Limit x als `Company.where('lower(name) LIKE ?', '%fraunhofer%').count` alle Vorschläge angezeigt.
   - Wenn die Anzahl der Vorschläge größer ist als das Limit, dann werden entweder die Vorschläge angezeigt, die
      - entweder am kürzesten sind. Hier werden bei mehreren gleichen Suchen die selben Ergebnisse angezeigt.
      - oder mit der Suche am nächsten verwandt sind.
      - oder zufällig aus den Ergebnissen ausgewählt werden.

**Comment by bkleinen** [comment]
In der bisherigen Lösung ist es möglich, in der URL beliebige Company/CompanyAddress-IDs von Hand einzusetzen.

**Comment by JuliaZamaitat** [comment]
@bkleinen Wo genau tritt den das Problem auf, dass  man die URL von Hand einsetzen kann? In den Abilities ist edit, show und update eigentlich auf den Nutzer beschränkt.
