### ISSUE TITLE
Move Test Coverage back to 100%

### ISSUE THREAD

**Issue by bkleinen** [imimap/imimap#425]
Immer zuerst in das aktuelle coverage/index.html gucken :)

- [x] app/controllers/company_addresses_controller.rb 	35.85 % 	112 	53 	19 	34 	0.4
- [x] app/admin/orientations.rb 	37.5 % 	27 	16 	6 	10 	0.4
- [x] app/admin/reading_profs.rb 	37.5 % 	27 	16 	6 	10 	0.4
- [x] app/admin/programming_languages.rb 	41.18 % 	28 	17 	7 	10 	0.4
- [x] spec/support/session_helpers.rb 	42.86 % 	15 	7 	3 	4 	0.4
- [ ] spec/features/user_student_association/internship_creation_spec.rb 	50.0 % 	11 	6 	3 	3 	0.5
- [ ] app/controllers/users_controller.rb 	56.0 % 	47 	25 	14 	11 	1.0
- [ ] app/controllers/internship_offers_controller.rb 	57.89 % 	45 	19 	11 	8 	1.2
- [x] app/uploaders/uploader.rb 	66.67 % 	12 	3 	2 	1 	0.7
- [x] app/helpers/company_addresses_helper.rb 	71.43 % 	39 	14 	10 	4 	2.5
- [ ] app/controllers/internships_controller.rb 	75.89 % 	238 	112 	85 	27 	6.9
- [x] app/admin/companies.rb 	76.19 % 	38 	21 	16 	5 	2.4
- [x] app/helpers/complete_internships_helper.rb 	81.82 % 	24 	11 	9 	2 	17.5
- [ ] app/uploaders/internship_report_uploader.rb 	83.33 % 	58 	6 	5 	1 	14.3
- [ ] spec/factories/attachments.rb 	83.33 % 	20 	6 	5 	1 	0.8
- [ ] app/models/internship.rb 	85.0 % 	104 	60 	51 	9 	7.8
- [ ] app/controllers/application_controller.rb 	87.88 % 	72 	33 	29 	4 	40.6
- [ ] lib/ldap/ldaphtw_adapter.rb 	90.57 % 	112 	53 	48 	5 	18.6
- [ ] app/helpers/complete_internship_data_helper.rb 	90.91 % 	117 	66 	60 	6 	6.6
- [ ] app/models/internship_duration.rb 	92.86 % 	47 	28 	26 	2 	14.4
- [ ] config/initializers/feature_toggle.rb 	93.33 % 	34 	15 	14 	1 	38.1
- [x] app/controllers/complete_internships_controller.rb 	93.65 % 	125 	63 	59 	4 	10.6
- [x] app/controllers/companies_controller.rb 	94.74 % 	125 	57 	54 	3 	2.4
- [ ] app/helpers/application_helper.rb 	95.24 % 	45 	21 	20 	1 	65.0
- [ ] app/admin/semesters.rb 	95.45 % 	36 	22 	21 	1 	1.1
- [ ] app/models/company_address.rb 	95.45 % 	49 	22 	21 	1 	100.5
- [ ] spec/rails_helper.rb 	95.45 % 	77 	22 	21 	1 	14.2
- [ ] spec/features/admin/03_student/02_index_spec.rb 	97.14 % 	55 	35 	34 	1 	1.4
- [x] app/models/user.rb 	98.04 % 	103 	51 	50 	1 	30.1

**Comment by bkleinen** [comment]
All Files (95.58% covered at 10.19 hits/line) 
- d.h. es wäre schön, wenn jede_r von Ihnen die Coverage um 1,5 % heben würde:
- eigener Branch test_coverage_bk / st / jz / lu 
- oben dateien aussuchen, abhaken und hier in ein kommentar hier übernehmen
- bis test coverage um 1,5% gestiegen ist

**Comment by bkleinen** [comment]
Ich übernehme: 

- [ ]  app/admin/companies.rb 76.19 % 38 21 16 5 2.4

**Comment by bkleinen** [comment]
<img width="482" alt="grafik" src="https://user-images.githubusercontent.com/627119/64171861-fc2e2200-ce53-11e9-9fe9-21a410834cc7.png">

**Comment by thuemmels** [comment]
Started with 95.59%
Ich übernehme:

- [ ]  app/controllers/company_addresses_controller.rb 35.85 % 112 53 19 34 0.4

in new branch coverage_st_2019_09:
All Files (95.59% covered at 10.22 hits/line)

**Comment by JuliaZamaitat** [comment]
Started with 95.51%
Ich übernehme:
- [ ]  app/controllers/complete_internships_controller.rb 93.65 % 125 63 59 4 10.6
- [ ] app/helpers/complete_internships_helper.rb 81.82 % 24 11 9 2 17.5
- [ ]  app/helpers/company_addresses_helper.rb 71.43 % 39 14 10 4 

im new branch coverage_jz_2019_09
All Files (95.51% covered at 10.19 hits/line)

**Comment by bkleinen** [comment]
started with 96,86 % in coverage_bk_2019_10
app/admin/orientations.rb 37.5 % 27 16 6 10 0.4
app/admin/reading_profs.rb 37.5 % 27 16 6 10 0.4
app/admin/programming_languages.rb 41.18 % 28 17 7 10 0.4

**Comment by JuliaZamaitat** [comment]
Unter spec_helper.rb findet man die aktuelle Coverage, die vorgegeben ist.

**Comment by bkleinen** [comment]
agreed to update minimum coverage in spec_helper.rb whenever possible.
