### ISSUE TITLE
Language Toggle does not work in CompanyAddress Form

### ISSUE THREAD

**Issue by bkleinen** [imimap/imimap#427]
the called url is (revealing the source of the problem - internship_id at the end)
http://localhost:3000/en/newAddress/63?internship_id=internship_id

**Comment by JuliaZamaitat** [comment]
Ich konnte den Fehler nicht reproduzieren, bei mir hat alles funktioniert. Wie kamen Sie denn auf diesen Link?

**Comment by bkleinen** [comment]
http://localhost:3000/de/newAddress/61?internship_id=62
- jetzt tut es. Ich schliesse den Bug.
