### ISSUE TITLE
Navigation in Praktikumseingabe unklar

### ISSUE THREAD

**Issue by bkleinen** [imimap/imimap#491]
Wenn die einzelnen Teile ausgefüllt werden, fehlt ein "Zurück zur Übersicht" knopf oder soetwas wie "wurde gespeichert. Zurück zur Übersicht"

**Comment by lotteunckell** [comment]
@bkleinen um welche Views geht es da genau? Um die kompliziertere Viewfolge beim Anlegen der Firmendetails?
