### ISSUE TITLE
Schwerpunkte und Programmiersprachen

### ISSUE THREAD

**Issue by bkleinen** [imimap/imimap#502]
Kommentarfeld für Internship hinzufügen, in dem fehlende Programmiersprachen und Schwerpunkte eingetragen werden können
- [x] Orientation in Schwerpunkt umbenennen (ist auch in active admin so)
- [ ] Kommentarfeld einfügen

**Comment by JuliaZamaitat** [comment]
@bkleinen Wir wären gegen das Kommentarfeld, aus verschiedenen Gründen:

- die Wahrscheinlichkeit, dass ein Studi eine andere von den vorgeschlagenen Sprachen auswählen möchte, ist relativ gering. Wenn das einmal vorkommt unter unseren Studis, ist das dann überhaupt für statistische Zwecke relevant? Wir würden per Hand noch welche hinzufügen, sodass wir die populärsten Sprachen alle abgedeckt haben
- Wenn wir ein Kommentarfeld einfügen würden, müssten wir vor jedem Speichern des Formulars überprüfen, ob eine neue Sprache erstellt werden muss, ob es diese vielleicht schon gibt und erst dann das Formular speichern. Das sieht nach ziemlich viel Overhead aus für wenig Nutzen.
- Für die Suche nach Praktika mit spezifischen Programmiersprachen könnte man für diesen Zweck ein "Andere" Feld in die Auswahl mit aufnehmen, und dann entsprechend eine begrenzte Anzahl an Firmen anzeigen lassen, wenn der Studi seine Wunschprogrammiersprache nicht in der Liste findet.
