### ISSUE TITLE
Einverständniserklärung von Studis

### ISSUE THREAD

**Issue by lotteunckell** [imimap/imimap#508]
Einfügen einer Einverständniserklärung, damit wir die Praktikumsdaten über die Dauer des Praktikums hinaus speichern können

**Comment by JuliaZamaitat** [comment]
- [ ] Wohin soll die Einverständniserklärung?
- [ ] Was soll in dem Text dazu stehen?
- [ ] Brauchen wir das auch für juristische Personen, also die Firmen? --> eigentlich ja keine personenbezogenen Daten, lediglich die Verbindung, dass dort schon ein IMI war
- [ ] Müssen wir die Einverständniserklärung nachträglich von allen Studis einfordern?

**Comment by lotteunckell** [comment]
https://www.impulse.de/recht-steuern/rechtsratgeber/dsgvo-einwilligungserklaerung/7305229.html

**Comment by JuliaZamaitat** [comment]
Gehört zu: 

https://github.com/imimap/imimap/issues/396
