### ISSUE TITLE
Students without Users can't log in

### ISSUE THREAD

**Issue by lotteunckell** [imimap/imimap#511]

**Comment by bkleinen** [comment]
E, [2019-11-28T09:45:13.580038 #5] ERROR -- : [d0ba1c76-130e-4b51-9f02-1bd649eef62b] -- ldap -- could not connect to host login.htw-berlin.de
E, [2019-11-28T09:45:13.580102 #5] ERROR -- : [d0ba1c76-130e-4b51-9f02-1bd649eef62b] no implicit conversion of true into String

~
bash-4.4# ping login.htw-berlin.de
PING login.htw-berlin.de (141.45.11.193): 56 data bytes
64 bytes from 141.45.11.193: seq=0 ttl=124 time=2.051 ms
64 bytes from 141.45.11.193: seq=1 ttl=124 time=0.605 ms
