### ISSUE TITLE
suche für admins

### ISSUE THREAD

**Issue by lotteunckell** [imimap/imimap#568]
- [x] Ergebnislimit: Hinweis braucht es nicht für Admins
- [x] Link zum Praktikum im Adminbereich

**Comment by JuliaZamaitat** [comment]
TODO: 

- [ ] Test für Hinweis hidden für Admins
- [ ] Test für Link zum Adminbereich für Admins

**Comment by JuliaZamaitat** [comment]
i568_search_for_admins
